# This is a basic workflow to help you get started with Actions

name: Deploy to EKS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  pull_request:
    branches: [master]

jobs:
  
  deploy:
    
    name: Build Image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Install Kubecontrol
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.1'
      id: install
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push images to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: docker_nodejs_demo
        IMAGE_TAG: ${{ github.sha}}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY

    - name: Update Kube config
      run: aws eks update-kubeconfig --name docker_nodejs_demo --region us-east-2
        
    - name: Deploy image to amazon EKS
      run: |
        kubectl apply -f /home/samir/Desktop/projects/docker_nodejs_demo/eks/aws-auth.yaml
        kubectl apply -f /home/samir/Desktop/projects/docker_nodejs_demo/eks/deployment.yaml
        kubectl apply -f /home/samir/Desktop/projects/docker_nodejs_demo/eks/service.yaml


